apiVersion: v1                                                                  
kind: Service                                                                   
metadata:                                                                       
  name: hello-world                                                              
  labels:                                                                       
    app.kubernetes.io/name: hello-world                                          
spec:                                                                           
  ports:                                                                        
  - port: 8080                                                                  
    targetPort: 80                                                            
  selector:                                                                     
    app.kubernetes.io/name: hello-world 
