apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    # nodePort: 30080 # Optional: Kubernetes assigns a port if this is omitted
  selector:
    app.kubernetes.io/name: hello-world